(lang dune 3.11)

(name zutils)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name")

(maintainers "Maintainer Name")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name zutils)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
  ocaml
  dune
  (spectrum (>= 0.6.0))
  (rocq-runtime (>= 9.0.1)))
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
